version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - 80:${PORT}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
